import {
    faCloud,
    faBoltLightning,
    faCloudSunRain,
    faCloudSun,
    faCloudRain,
    faCloudShowersHeavy,
    faSnowflake,
    faSun,
    faMoon,
    faSmog
} from '@fortawesome/free-solid-svg-icons';

const weathers = {
    "clearsky_day": faSun,
    "clearsky_night": faMoon,
    "clearsky_polartwilight": faMoon,
    "fair_day": faCloudSun,
    "fair_night": faMoon,
    "fair_polartwilight": faMoon,
    "lightssnowshowersandthunder_day": faSnowflake,
    "lightssnowshowersandthunder_night": faSnowflake,
    "lightssnowshowersandthunder_polartwilight": faSnowflake,
    "lightsnowshowers_day": faSnowflake,
    "lightsnowshowers_night": faSnowflake,
    "lightsnowshowers_polartwilight": faSnowflake,
    "heavyrainandthunder": faBoltLightning,
    "heavysnowandthunder": faBoltLightning,
    "rainandthunder": faBoltLightning,
    "heavysleetshowersandthunder_day": faBoltLightning,
    "heavysleetshowersandthunder_night": faBoltLightning,
    "heavysleetshowersandthunder_polartwilight": faBoltLightning,
    "heavysnow": faSnowflake,
    "heavyrainshowers_day": faCloudShowersHeavy,
    "heavyrainshowers_night": faCloudShowersHeavy,
    "heavyrainshowers_polartwilight": faCloudShowersHeavy,
    "lightsleet": faSnowflake,
    "heavyrain": faCloudShowersHeavy,
    "lightrainshowers_day": faCloudSunRain,
    "lightrainshowers_night": faCloudSunRain,
    "lightrainshowers_polartwilight": faCloudSunRain,
    "heavysleetshowers_day": faSnowflake,
    "heavysleetshowers_night": faSnowflake,
    "heavysleetshowers_polartwilight": faSnowflake,
    "lightsleetshowers_day": faSnowflake,
    "lightsleetshowers_night": faSnowflake,
    "lightsleetshowers_polartwilight": faSnowflake,
    "snow": faSnowflake,
    "heavyrainshowersandthunder_day": faBoltLightning,
    "heavyrainshowersandthunder_night": faBoltLightning,
    "heavyrainshowersandthunder_polartwilight": faBoltLightning,
    "snowshowers_day": faSnowflake,
    "snowshowers_night": faSnowflake,
    "snowshowers_polartwilight": faSnowflake,
    "fog": faSmog,
    "snowshowersandthunder_day": faSnowflake,
    "snowshowersandthunder_night": faSnowflake,
    "snowshowersandthunder_polartwilight": faSnowflake,
    "lightsnowandthunder": faSnowflake,
    "heavysleetandthunder": faSnowflake,
    "lightrain": faCloudRain,
    "rainshowersandthunder_day": faBoltLightning,
    "rainshowersandthunder_night": faBoltLightning,
    "rainshowersandthunder_polartwilight": faBoltLightning,
    "rain": faCloudRain,
    "lightsnow": faSnowflake,
    "lightrainshowersandthunder_day": faBoltLightning,
    "lightrainshowersandthunder_night": faBoltLightning,
    "lightrainshowersandthunder_polartwilight": faBoltLightning,
    "heavysleet": faSnowflake,
    "sleetandthunder": faBoltLightning,
    "lightrainandthunder": faBoltLightning,
    "sleet": faSnowflake,
    "lightssleetshowersandthunder_day": faBoltLightning,
    "lightssleetshowersandthunder_night": faBoltLightning,
    "lightssleetshowersandthunder_polartwilight": faBoltLightning,
    "lightsleetandthunder": faBoltLightning,
    "partlycloudy_day": faCloudSun,
    "partlycloudy_night": faCloudSun,
    "partlycloudy_polartwilight": faCloudSun,
    "sleetshowersandthunder_day": faBoltLightning,
    "sleetshowersandthunder_night": faBoltLightning,
    "sleetshowersandthunder_polartwilight": faBoltLightning,
    "rainshowers_day": faCloudRain,
    "rainshowers_night": faCloudRain,
    "rainshowers_polartwilight": faCloudRain,
    "snowandthunder": faBoltLightning,
    "sleetshowers_day": faSnowflake,
    "sleetshowers_night": faSnowflake,
    "sleetshowers_polartwilight": faSnowflake,
    "cloudy": faCloud,
    "heavysnowshowersandthunder_day": faBoltLightning,
    "heavysnowshowersandthunder_night": faBoltLightning,
    "heavysnowshowersandthunder_polartwilight": faBoltLightning,
    "heavysnowshowers_day": faSnowflake,
    "heavysnowshowers_night": faSnowflake,
    "heavysnowshowers_polartwilight": faSnowflake
}

export function getWeatherIcon(weather) {
    return weathers[weather];
}